apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-kgi5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-kgi5
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-kgi5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-kgi5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-kgi5
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mmsu-tenant/rhtap-demo-app/hacbs-test-project-kgi5@sha256:e7609a63ff0815ac3edbc363107d92440d579d609fc9ccfdd7beccc41d2eec9c
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
