apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-kgi5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mmsu-tenant/rhtap-demo-app/hacbs-test-project-kgi5@sha256:e7609a63ff0815ac3edbc363107d92440d579d609fc9ccfdd7beccc41d2eec9c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
